### ISSUE TITLE
Is there a num_iterations argument in offline examples?

### ISSUE THREAD

**Issue by zgzhikaru** [google-deepmind/acme#315]
For examples in [https://github.com/google-deepmind/acme/tree/master/examples/offline](examples/offline) directory, all scripts follow a convention of nonterminating outer-most loops such as
<img width="433" alt="Screenshot 2023-12-16 at 12 15 44 PM" src="https://github.com/google-deepmind/acme/assets/32402013/c5f57886-9e12-46c7-b11d-309d2dbeca49">
]()
in contrast to the experiments.run_experiment(_) convention in other examples and tutorials. 
 
I wonder is this intended for manually terminating the process? Did I missed some important details?

**Comment by ethanluoyc** [comment]
I think those are meant as examples illustrating how Acme agents work in the offline setting. You can write your own learning loop or use the experiments subpackage, which provides reasonable default behavior.

**Comment by zgzhikaru** [comment]
Thank you for clarifying and sorry for this trivial issue.
